# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "database_schema/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
patch_file = "database_schema/src/schema.patch"

[migrations_directory]
dir = "./migrations"
