version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/nats.conf
    restart: always
    command: ["-js", "--config", "/nats.conf"]

  firestore_reader:
    build:
      context: .
      dockerfile: firestore_reader.Dockerfile
    environment:
      - NATS_HOST=nats://nats:4222
      - BIND_FIRESTORE_READER=0.0.0.0:8000
      - SETTINGS_COLLECTION=${SETTINGS_COLLECTION}
      - GOOGLE_APPLICATION_CREDENTIALS=./cert.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - ./cert.json:/usr/src/app/cert.json
    restart: unless-stopped
    ports:
      - "8001:8000"
    depends_on:
      - nats

  jetstream_reader:
    build:
      context: .
      dockerfile: jetstream_reader.Dockerfile
    environment:
      - NATS_HOST=nats://nats:4222
      - BIND_JETSTREAM_READER=0.0.0.0:8000
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - SENTRY_DSN=${SENTRY_DSN}
    restart: unless-stopped
    ports:
      - "8002:8000"
    depends_on:
      - nats
      - firestore_reader

  notifier:
    build:
      context: .
      dockerfile: notifier.Dockerfile
    environment:
      - NATS_HOST=nats://nats:4222
      - BIND_NOTIFIER=0.0.0.0:8000
      - GOOGLE_APPLICATION_CREDENTIALS=./cert.json
      - MOCK=${MOCK}
      - RUST_LOG=info,notifier:debug
      - RUST_BACKTRACE=1
      - SENTRY_DSN=${SENTRY_DSN}
      - LOKI_URL=${LOKI_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./cert.json:/usr/src/app/cert.json
    restart: unless-stopped
    ports:
      - "8003:8000"
    depends_on:
      - nats
      - firestore_reader
      - jetstream_reader