version: '3.8'

services:
  notifier:
    build:
      context: .
      dockerfile: notifier.Dockerfile
    volumes:
      - ./apps/notifier/src:/app/apps/notifier/src
      - ./packages:/app/packages
      - ./cert.json:/app/cert.json
      - ./processed_posts.pickle:/app/processed_posts.pickle
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cert.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - MOCK=True
      - SETTINGS_COLLECTION=${SETTINGS_COLLECTION}
      - SENTRY_DSN=${SENTRY_DSN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 5s
      retries: 3

  jetstream_reader:
    build:
      context: .
      dockerfile: jetstream_reader.Dockerfile
    volumes:
      - ./apps/jetstream-reader/src:/app/apps/jetstream-reader/src
      - ./packages:/app/packages
    environment:
      - NOTIFIER_SERVER=http://notifier:8000
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "9000:9000"
    depends_on:
      notifier:
        condition: service_healthy

  manual_polling:
    build:
      context: .
      dockerfile: manual_polling.Dockerfile
    volumes:
      - ./apps/manual-polling/src:/app/apps/manual-polling/src
      - ./packages:/app/packages
    environment:
      - NOTIFIER_SERVER=http://notifier:8000
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "9000:9000"
    depends_on:
      notifier:
        condition: service_healthy