version: '3.8'

services:
  notifier:
    build:
      context: ./../
      dockerfile: notifier.Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cert.json
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - MOCK=${MOCK}
      - SETTINGS_COLLECTION=${SETTINGS_COLLECTION}
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - ../cert.json:/app/cert.json
      - ../processed_posts.pickle:/app/processed_posts.pickle
    ports:
      - "8000:8000"
    restart: always
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
  manual_polling:
    build:
      context: ./../
      dockerfile: manual_polling.Dockerfile
    environment:
      - NOTIFIER_SERVER=http://notifier:8000
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "9000:9000"
    restart: always
    network_mode: "host"
  jetstream_reader:
    build:
      context: ./../
      dockerfile: jetstream_reader.Dockerfile
    environment:
      - NOTIFIER_SERVER=http://notifier:8000
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "9001:9000"
    restart: always
    network_mode: "host"
