[package]
name = "database_schema"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
diesel = { version = "2.2.8", features = ["postgres", "chrono"] }
serde = "1.0.217"
serde_json = "1.0.138"
