[project]
name = "async-utils"
version = "0.1.0"
description = "Functions and utilities for async stuff."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/async_utils"]