[project]
name = "bluesky-utils"
version = "0.1.0"
description = "Utility functions and tools for bluesky."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bluesky_utils"]
