name: Publish Web Server Docker Container

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_web_server.yml'
      - 'web_server.Dockerfile'
      - 'web_server/**'
      - 'database_schema/**'
  workflow_dispatch:


jobs:
  test_web_server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }} --package web_server

  publish_web_server:
    name: Publish Web Server
    runs-on: ubuntu-latest
    needs: test_web_server
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ci
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}
          registry: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./web_server.Dockerfile
          push: true
          tags: ${{ secrets.PRIVATE_DOCKER_REGISTRY }}/ci/blue_notify_web_server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
