name: Redeploy latest servers

on:
  workflow_dispatch:
  workflow_run:
    workflows:
        - Publish Notifier Docker Container
        - Publish Web Server Docker Container
        - Publish Jetstream Reader Docker Container
        - Publish Firestore Reader Docker Container
    types:
      - completed
    branches:
      - main


jobs:
  deploy_latest_servers:
    name: Redeploy latest servers
    if: ${{ github.event.action.workflow_dispatch || (github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.MAIN_BLUENOTIFY_SERVER_USER }}
          SSH_KEY: ${{ secrets.MAIN_BLUENOTIFY_SERVER_KEY }}
          SSH_HOST: ${{ secrets.MAIN_BLUENOTIFY_SERVER }}

      - name: Start the server
        run: ssh prod './update_services.sh'